services:
  qbittorrent:
    image: linuxserver/qbittorrent:4.6.7
    environment:
      TZ: Asia/Taipei # 設定時區
    volumes:
      - /volume1/docker/qbittorrent/config:/config
      - /volume1/downloader/qbittorrent:/downloads
    restart: always
    networks:
      - macvlan

networks:
  macvlan:
    external: true
