version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - /volume1/docker/qdrant/data:/qdrant/storage
    networks:
      - macvlan

networks:
  macvlan:
    external: true
