services:
  postman:
    image: postman/newman
    restart: always
    volumes:
      - 
    networks:
      - macvlan
      # - npm_bridge

networks:
  macvlan:
    external: true
  # npm_bridge:
  #   external: true