services:
  adguardhome:
    image: adguard/adguardhome
    restart: always
    volumes:
      - /volume1/docker/dns/adguardhome/confdir:/opt/adguardhome/conf
      - /volume1/docker/dns/adguardhome/workdir:/opt/adguardhome/work
      - /volume1/docker/npm/letsencrypt/archive/npm-1:/opt/adguardhome/certs
    ports:
      - 53:53
      - 853:853
    networks:
      macvlan:
        ipv4_address: 192.168.50.251

networks:
  macvlan:
    external: true