services:
  # 對外的 DNS 服務
  adguardhome:
    image: adguard/adguardhome
    restart: always
    volumes:
      - /volume1/docker/dns/adguardhome/confdir:/opt/adguardhome/conf
      - /volume1/docker/dns/adguardhome/workdir:/opt/adguardhome/work
      - /volume1/docker/npm/letsencrypt/archive/npm-1:/opt/adguardhome/certs
    network_mode: host

  # 解析 docker namespace
  npm:
    image: adguard/adguardhome
    restart: always
    ports:
      - 10000:53
      - 10001:3000
    networks:
      - npm

networks:
  npm:
    external: true
