services:
  # 對外的 DNS 服務
  home:
    image: adguard/adguardhome
    restart: always
    volumes:
      - /volume1/docker/dns/adguardhome/confdir:/opt/adguardhome/conf
      - /volume1/docker/dns/adguardhome/workdir:/opt/adguardhome/work
      - /volume1/docker/npm/letsencrypt/archive/npm-1:/opt/adguardhome/certs
    network_mode: host

  

networks:
  npm:
    external: true