services:
  plex:
    image: linuxserver/plex
    restart: always
    networks:
      - npm
    volumes:
      - /volume1/docker/plex/config:/config
      - /volume1/docker/plex/movies:/movies
      - /volume1/docker/plex/tv:/tv

networks:
  npm:
    external: true
