services:
  plex:
    image: linuxserver/plex
    restart: always
    networks:
      - macvlan
      # - npm_bridge
    volumes:
      - /volume1/docker/plex/config:/config
      - /volume1/docker/plex/movies:/movies
      - /volume1/docker/plex/tv:/tv

networks:
  macvlan:
    external: true
  # npm_bridge:
  #   external: true
