services:
  mem0_store:
    image: qdrant/qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - /volume1/docker/open-memory-mcp/qdrant:/mem0/storage

  openmemory-mcp:
    image: mem0/openmemory-mcp:latest
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USER=sepher
      - QDRANT_HOST=mem0_store
      - QDRANT_PORT=6333
    depends_on:
      - mem0_store
    ports:
      - "8765:8765"
    networks:
      - macvlan

  openmemory-ui:
    image: mem0ai/openmemory-ui:latest
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=https://omui.i23iv.cc
      - NEXT_PUBLIC_USER_ID=sepher
    ports:
      - "3000:3000"
    networks:
      - macvlan

networks:
  macvlan:
    external: true
    