services:
  ubuntu:
    build: 
      context: .
      dockerfile: dockerfile
    tty: true
    stdin_open: true
    restart: always
    environment:
      TZ: Asia/Taipei
    networks:
      npm:

networks:
  npm:
    external: true