services:
  xampp:
    image: kalilinux/kali-rolling
    restart: always
    tty: true
    stdin_open: true
    networks:
      - macvlan
      # - npm_bridge

networks:
  macvlan:
    external: true
  # npm_bridge:
  #   external: true