services:
  grafana:
    image: grafana/grafana
    restart: always
    volumes:
      - /volume1/docker/grafana:/var/lib/grafana
    environment:
      - TZ=Asia/Taipei # 設定時區
    networks:
      - macvlan

networks:
  macvlan:
    external: true
