services:
  grafana:
    image: grafana/grafana
    restart: always
    volumes:
      - /volume1/docker/grafana/grafana:/var/lib/grafana
    networks:
      - macvlan
      # - npm_bridge

  loki:
    image: grafana/loki
    restart: always
    volumes:
      - /volume1/docker/grafana/loki:/loki
    networks:
      - macvlan
      # - npm_bridge

networks:
  macvlan:
    external: true
  # npm_bridge:
  #   external: true
