services:
  grafana:
    image: grafana/grafana
    restart: always
    volumes:
      - /volume1/docker/grafana/grafana:/var/lib/grafana
    networks:
      - npm

  loki:
    image: grafana/loki
    restart: always
    volumes:
      - /volume1/docker/grafana/loki:/loki
    networks:
      - npm

networks:
  npm:
    external: true
