services:
  grafana:
    image: grafana/grafana
    restart: always
    volumes:
      - /volume1/docker/grafana/grafana:/var/lib/grafana
    networks:
      - macvlan

networks:
  macvlan:
    external: true
