services:
  grafana:
    image: grafana/grafana
    restart: always
    volumes:
      - /volume1/docker/grafana:/var/lib/grafana
    networks:
      - npm_bridge

networks:
  npm_bridge:
    driver: bridge
