services:
  # 解析 docker namespace
  docker:
    image: adguard/adguardhome
    restart: always
    volumes:
      - /volume1/docker/dns/docker/confdir:/opt/adguardhome/conf
      - /volume1/docker/dns/docker/workdir:/opt/adguardhome/work
    ports:
      - 10000:53
      - 10001:3000
    networks:
      - npm

networks:
  npm:
    external: true