services:
  wordpress:
    image: wordpress:latest
    restart: always
    volumes:
      - /volume1/docker/wordpress/html:/var/www/html
    networks:
      - npm

networks:
  npm:
    external: true
