services:
  wordpress:
    image: wordpress:latest
    restart: always
    volumes:
      - $WP_HTML:/var/www/html
    networks:
      - macvlan
      # - npm_bridge

networks:
  macvlan:
    external: true
  # npm_bridge:
  #   external: true
