services:
  wordpress:
    image: wordpress:latest
    restart: always
    volumes:
      - $WP_HTML:/var/www/html
    networks:
      # - npm_bridge
      - macvlan

networks:
  macvlan:
    external: true
  # npm_bridge:
  #   external: true
