services:
  wordpress:
    image: wordpress:latest
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /volume1/docker/wordpress/html:/var/www/html
    networks:
      - macvlan

networks:
  macvlan:
    external: true
