services:
  wordpress:
    image: wordpress:latest
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    dns:
      - host.docker.internal
    volumes:
      - /volume1/docker/wordpress/html:/var/www/html
    networks:
      - npm

networks:
  npm:
    external: true
