services:
  cadvisor:
    image: google/cadvisor
    restart: always
    environment:
      TZ: Asia/Taipei # 設定時區
    networks:
      - macvlan
      # - npm

networks:
  macvlan:
    external: true
  # npm:
  #   external: true