services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      TZ: Asia/Taipei # 設定時區
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - /volume1/docker/db/mariadb/mysql:/var/lib/mysql
    networks:
      - macvlan

  phpmyadmin:
    image: phpmyadmin
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: Asia/Taipei # 設定時區
      PMA_HOST: host.docker.internal
      UPLOAD_LIMIT: 500M
    networks:
      - macvlan

networks:
  macvlan:
    external: true