services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      TZ: Asia/Taipei # 設定時區
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - /volume1/docker/db/mariadb/mysql:/var/lib/mysql
    networks:
      macvlan:
        ipv4_address: 192.168.50.252


  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      TZ: Asia/Taipei # 設定時區
      PMA_HOST: 192.168.50.252
      UPLOAD_LIMIT: 500M
    networks:
      - macvlan

networks:
  macvlan:
    external: true