services:
  adh_1:
    image: adguard/adguardhome
    restart: always
    volumes:
      - /volume1/docker/adguardhome/1/confdir:/opt/adguardhome/conf
      - /volume1/docker/adguardhome/1/workdir:/opt/adguardhome/work
      - /volume1/docker/npm/data/custom_ssl/npm-2:/opt/adguardhome/certs
    networks:
      - macvlan
      - npm

  adh_2:
    image: adguard/adguardhome
    restart: always
    volumes:
      - /volume1/docker/adguardhome/2/confdir:/opt/adguardhome/conf
      - /volume1/docker/adguardhome/2/workdir:/opt/adguardhome/work
    networks:
      - macvlan
      - npm

networks:
  macvlan:
    external: true
  npm:
    external: true
