services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - $DB_DATA:/var/lib/mysql
    networks:
      - npm_bridge

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb-mariadb-1
      - UPLOAD_LIMIT=100M
    networks:
      - npm_bridge

  game:
    image: node
    restart: always
    networks:
      - npm_bridge

networks:
  npm_bridge:
    external: true