services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      TZ: Asia/Taipei # 設定時區
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - $DB_DATA:/var/lib/mysql
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "3"
    networks:
      macvlan:
        ipv4_address: 192.168.50.251
        npm:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      TZ: Asia/Taipei # 設定時區
      PMA_HOST: mariadb-mariadb-1
      UPLOAD_LIMIT: 500M
    networks:
      - npm

networks:
  npm:
    external: true
  macvlan:
    external: true