services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - $DB_DATA:/var/lib/mysql
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "3"
    networks:
      - macvlan
      # - npm_bridge

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb-mariadb-1
      - UPLOAD_LIMIT=100M
    networks:
      - macvlan
      # - npm_bridge

networks:
  macvlan:
    external: true
  # npm_bridge:
  #   external: true