services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    tty: true
    stdin_open: true
    ports:
      - 8080:80 # HTTP
      - 8443:443 # HTTPS
      - 8081:81 # Admin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Asia/Taipei # 設定時區
    volumes:
      - /volume1/docker/npm/data:/data
      - /volume1/docker/npm/letsencrypt:/etc/letsencrypt
    networks:
      macvlan:
        ipv4_address: 192.168.50.251
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  macvlan:
    external: true
