services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    tty: true
    stdin_open: true
    networks:
      - npm
        # ipv4_address: $NPM_MACVLAN_IP
    environment:
      - TZ=Asia/Taipei # 設定時區
    volumes:
      - $NPM_DATA:/data
      - $NPM_LETSENCRYPT:/etc/letsencrypt

networks:
  npm:
    external: true