services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    tty: true
    stdin_open: true
    network_mode: host
    ports:
      - 80:80
      - 81:81
      - 443:443
    environment:
      - TZ=Asia/Taipei # 設定時區
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - $NPM_DATA:/data
      - $NPM_LETSENCRYPT:/etc/letsencrypt
