services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    tty: true
    stdin_open: true
    networks:
      - npm
    ports:
      - 8080:80
      - 8181:81
      - 8443:443
    environment:
      - TZ=Asia/Taipei # 設定時區
    volumes:
      - $NPM_DATA:/data
      - $NPM_LETSENCRYPT:/etc/letsencrypt

networks:
  npm:
    external: true
